extra-y += u-bootz u-bootz.bin
obj-y += start.o lowlevel_init.o main.o piggy.o decompress.o
lib-y := crc32.o memcpy.o memset.o serial_s3c4510b.o

clean-files += piggy_data *.a *.o *.su .*.cmd .*.d

quiet_cmd_link_elf = LD      $@
      cmd_link_elf = $(LD) $(KBUILD_LDFLAGS) -g \
                           -T $(obj)/u-bootz.lds \
                           $< -o $@ $(obj)/built-in.o $(obj)/lib.a \
                           -L $(shell dirname `$(CC) $(CFLAGS) -print-libgcc-file-name`) -lgcc

$(obj)/u-bootz: $(addprefix $(obj)/,$(obj-y))
	$(call if_changed,link_elf)

$(obj)/piggy.o: $(obj)/piggy_data

$(obj)/piggy_data: u-boot.bin FORCE
	$(call if_changed,gzip)

CFLAGS_decompress.o += -I lib/zlib

$(obj)/crc32.o: lib/crc32.c
	$(call if_changed,cc_o_c)

$(obj)/memcpy.o: arch/arm/lib/memcpy.S
	$(call if_changed,as_o_S)

$(obj)/memset.o: arch/arm/lib/memset.S
	$(call if_changed,as_o_S)

$(obj)/serial_s3c4510b.o: drivers/serial/serial_s3c4510b.c
	$(call if_changed,cc_o_c)

$(obj)/%.bin: OBJCOPYFLAGS += -O binary
$(obj)/%.bin: $(obj)/%
	$(call if_changed,objcopy)
